api:
    results_per_page: 35
    
log:
    debug: True
    
mongo:
    host: localhost
    port: 27017
    db: adistools

rabbitmq:
    host: localhost
    port: 5672
    user: adistools-api
    password: password

