general:
    daemonize: false
    start_workers: True
    start_uwsgi_workers: True

log:
    debug: true

daemon:
    pid_file: /opt/adistools/adistools-concurrent.pid

uwsgi:
    uwsgi_executable_path: /opt/homebrew/bin/uwsgi
    uid: 7676
    gid: 7676

tasks:
    interval: 0.1

directories:
    main_directory: /opt/adistools
    workers_directory: /opt/adistools/workers
    logs_directory: /opt/adistools/logs
    ini_directory: /opt/adistools/uwsgi_inis
    modules_directory: /opt/adistools/modules
