worker_gpt2:
    model: sicken_v2.0.0
    tokenizer: sicken

log:
    debug: true

mongo:
    host: localhost
    port: 27017
    db: sicken

rabbitmq:
    host: localhost
    port: 5672
    user: sicken-worker_gpt2_chat
    password: password
