log:
    debug: true
    
socketio:
    host: "0.0.0.0"
    port: 10003
    secret: secret

rabbitmq:
    host: localhost
    port: 5672
    user: sicken-socketio_dispatcher
    password: password

redis:
    host: localhost
    port: 6379
    db: 0
