log:
  debug: true
mongo:
  host: localhost
  port: 27017
  db: adistools
rabbitmq:
  host: localhost
  port: 5672
  user: adistools-api
  password: password
redis:
  host: localhost
  port: 6379
  db: 0
socketio:
  host: "0.0.0.0"
  port: 10013
  secret: secret